Repository getgauge/taiko, pull requests merged in 2019-04, with the labels that each got.

#475 replace non-blocking space character with space before matching, #446
  lib/taiko.js
Labels: cla-signed, ready, ready for Development

#477 Handle event emitter
  lib/taiko.js
Labels: cla-signed, ready, ready for Development

#479 fixes check for input element when text is inlined, #319
  lib/taiko.js
Labels: cla-signed, ready, ready for Development

#484 Reports request failure for HTTP status codes 4xx and 5xx in <goto> API.
  lib/networkHandler.js
  lib/pageHandler.js
  lib/taiko.js
Labels: cla-signed, ready, ready for Development

#486 Tests for radioButton api
  .eslintrc
  .vscode/launch.json
  package-lock.json
  package.json
  test/unit-tests/data/.gitkeep
  test/unit-tests/radioButton.test.js
  test/unit-tests/test-util.js
Labels: cla-signed, ready, ready for Development

#493 Fixed TypeError: module.constructor._nodeModulePaths is not a functio…
  lib/util.js
Labels: cla-signed, ready

#489 453 reverse search
  .eslintrc
  lib/repl-search.js
  lib/repl.js
Labels: cla-signed, ready, ready for Development

#494 #321 handle textnode
  lib/taiko.js
  package-lock.json
  test/functional-tests/specs/ElementsAPI.spec
  test/functional-tests/specs/ElementsAPIIFrame.spec
  test/functional-tests/specs/browserActions.spec
  test/functional-tests/specs/positionalSelectors.spec
  test/functional-tests/specs/positionalSelectorsIFrame.spec
  test/functional-tests/tests/click.js
  test/functional-tests/tests/htmlElementAPI.js
  test/unit-tests/radioButton.test.js
  test/unit-tests/test-util.js
  test/unit-tests/textMatch.test.js
Labels: cla-signed, ready

#488 adding tests for checkbox
  .vscode/launch.json
  package-lock.json
  package.json
  test/unit-tests/checkbox.test.js
  test/unit-tests/radioButton.test.js
Labels: cla-signed, ready, ready for Development

#498 added unit test for openBrowser API
  test/unit-tests/openBrowser.test.js
Labels: cla-signed, ready

#502 setConfig API
  lib/api.json
  lib/config.js
  lib/helper.js
  lib/taiko.js
  test/unit-tests/config.test.js
Labels: cla-signed

#505 #300 get target from cri instead of creating new
  lib/taiko.js
Labels: cla-signed, ready

#499 Add raspberry pi trouble shooting section
  docs/layout/partials/toc.html
  docs/layout/partials/troubleshoot.html
Labels: cla-signed, ready

#506 Unit test for closerBrowser and textBox
  test/unit-tests/closeBrowser.test.js
  test/unit-tests/openBrowser.test.js
  test/unit-tests/textBox.test.js
Labels: cla-signed, ready

#509 483 Making runner's console log event based
  bin/runFile.js
  lib/helper.js
  lib/repl.js
  lib/taiko.js
  test/unit-tests/closeBrowser.test.js
  test/unit-tests/openBrowser.test.js
Labels: cla-signed, ready

#513 #511 Emit events on checkbox and radiobutton change
  lib/taiko.js
  test/unit-tests/checkbox.test.js
  test/unit-tests/radioButton.test.js
Labels: cla-signed, ready

#512 Taiko examples
  examples/.gitignore
  examples/01-file_upload.js
  examples/02-file_download.js
  examples/03-work-with-frames.js
  examples/04-windows-tabs.js
  examples/05-dropdown.js
  examples/06-basic-auth.js
  examples/07-dynamic-loading.js
  examples/README.md
  examples/browserLauncher.js
  examples/gifs/basic-auth.gif
  examples/gifs/dropdown.gif
  examples/gifs/dynamic-pages.gif
  examples/gifs/file-download.gif
  examples/gifs/file-upload.gif
  examples/gifs/frames.gif
  examples/gifs/windows.gif
  examples/package-lock.json
  examples/package.json
  examples/runner.js
  lib/repl.js
  package.json
Labels: cla-signed, ready

#514 Fix error message typo
  lib/taiko.js
  package-lock.json
  package.json
Labels: cla-signed, ready
