Repository getgauge/taiko, pull requests merged in 2019-02, with the labels that each got.

#385 Scroll issue fix
  docs/layout/assets/css/style.css
  docs/layout/assets/js/main.js
Labels: cla-signed, ready

#386 fix linting
  test/functional-tests/.eslintrc.json
  test/functional-tests/.prettierignore
  test/functional-tests/.prettierrc
  test/functional-tests/package-lock.json
  test/functional-tests/package.json
  test/functional-tests/tests/alert.js
  test/functional-tests/tests/assert.js
  test/functional-tests/tests/browserAction.js
  test/functional-tests/tests/checkBox.js
  test/functional-tests/tests/click.js
  test/functional-tests/tests/comboBox.js
  test/functional-tests/tests/htmlElementAPI.js
  test/functional-tests/tests/pageActions.js
  test/functional-tests/tests/selectors.js
  test/functional-tests/tests/textAPI.js
  test/functional-tests/tests/write.js
Labels: cla-signed, ready

#387 Adding missing tests
  test/functional-tests/specs/browserActions.spec
  test/functional-tests/specs/pageActions.spec
  test/functional-tests/tests/browserAction.js
  test/functional-tests/tests/click.js
  test/functional-tests/tests/pageActions.js
Labels: cla-signed, ready

#381 capture screenshot with selector
  lib/api.json
  lib/domHandler.js
  lib/taiko.js
Labels: cla-signed, ready

#383 get cookies from browser session
  lib/api.json
  lib/taiko.js
  test/functional-tests/specs/browserActions.spec
  test/functional-tests/tests/browserAction.js
Labels: cla-signed, ready

#390 #389 fix - skip Wait for blank page
  lib/api.json
  lib/taiko.js
Labels: cla-signed, ready

#392 consider screenorientation for emulateDevice else default to potrait
  lib/emulationHandler.js
Labels: cla-signed, ready

#398 fix #397 click on number
  lib/taiko.js
Labels: cla-signed, ready

#380 #362 Cleanup timeouts on closeBrowser
  lib/taiko.js
Labels: cla-signed, ready

#404 #403 Add troubleshooting section in docs
  docs/layout/page.html
  docs/layout/partials/toc.html
  docs/layout/partials/troubleshoot.html
Labels: cla-signed, ready

#407 JD: Removed unref from helper.js which was blocking Jest Runner
  lib/helper.js
Labels: cla-signed, ready

#408 Add options to skip wait for navigation
  lib/api.json
  lib/taiko.js
Labels: cla-signed, ready

#412 #334 Add initial debug logs for events
  docs/layout/partials/toc.html
  docs/layout/partials/troubleshoot.html
  lib/api.json
  lib/networkHandler.js
  lib/pageHandler.js
  lib/taiko.js
  package.json
Labels: cla-signed, ready

#415 [Docs]: Changing id for $ selector '$' -> 'dollar' #399
  docs/layout/assets/js/main.js
Labels: cla-signed, ready, ready for Development

#416 Using string function in XPath so that all the child text nodes are considered #409
  lib/taiko.js
Labels: cla-signed, ready, ready for Development

#422 Fix the quotation mark
  README.md
  docs/layout/partials/header.html
Labels: cla-signed, ready, ready for Development

#421 Incorporate commander.js to handle taiko command line args and flags.
  bin/runFile.js
  bin/taiko.js
  lib/taiko.js
  lib/util.js
  package-lock.json
  package.json
Labels: cla-signed, ready for Development

#424 refactor - proximity selector element search
  lib/api.json
  lib/proximityElementSearch.js
  lib/taiko.js
Labels: cla-signed, ready, ready for Development
