Repository getgauge/taiko, pull requests merged in 2020-07, with the labels that each got.

#1340 Update intercept to use fetch apis instead of network apis
  lib/handlers/fetchHandler.js
  lib/handlers/networkHandler.js
  lib/taiko.js
  package-lock.json
  package.json
  test/unit-tests/clearIntercept.test.js
  test/unit-tests/goto.test.js
  test/unit-tests/handlers/fetchHandler.test.js
  test/unit-tests/handlers/networkHandler.test.js
  test/unit-tests/intercept.test.js
Labels: ReleaseCandidate, bug

#1351 make global types available in repl #1349
  lib/repl/repl.js
Labels: bug

#1358 #279 Drag and drop support for html5 draggable elements
  .github/workflows/taiko.yml
  lib/actions/dragAndDrop.js
  lib/actions/pageActionChecks.js
  lib/actions/scrollTo.js
  lib/elementWrapper/elementWrapper.js
  lib/elements/element.js
  lib/handlers/inputHandler.js
  lib/taiko.js
  test/unit-tests/actions/pageActionChecks.test.js
  test/unit-tests/elements/element.test.js
Labels: feature

#1343 Migrate selectors to use css selector instead of xpath
  lib/elementSearch.js
  lib/elementWrapper/buttonWrapper.js
  lib/elementWrapper/checkBoxWrapper.js
  lib/elementWrapper/colorWrapper.js
  lib/elementWrapper/dollarWrapper.js
  lib/elementWrapper/dropDownWrapper.js
  lib/elementWrapper/elementWrapper.js
  lib/elementWrapper/elementWrapperFactory.js
  lib/elementWrapper/fileFieldWrapper.js
  lib/elementWrapper/helper.js
  lib/elementWrapper/imageWrapper.js
  lib/elementWrapper/linkWrapper.js
  lib/elementWrapper/listItemWrapper.js
  lib/elementWrapper/radioButtonWrapper.js
  lib/elementWrapper/rangeWrapper.js
  lib/elementWrapper/tableCellWrapper.js
  lib/elementWrapper/textBoxWrapper.js
  lib/elementWrapper/textWrapper.js
  lib/elementWrapper/timeFieldWrapper.js
  lib/helper.js
  lib/taiko.js
  package-lock.json
  package.json
  test/unit-tests/$.test.js
  test/unit-tests/checkbox.test.js
  test/unit-tests/clear.test.js
  test/unit-tests/dropDown.test.js
  test/unit-tests/filefield.test.js
  test/unit-tests/image.test.js
  test/unit-tests/link.test.js
  test/unit-tests/listItem.test.js
  test/unit-tests/radioButton.test.js
  test/unit-tests/range.test.js
  test/unit-tests/tablecell.test.js
  test/unit-tests/textBox.test.js
  test/unit-tests/textMatch.test.js
  test/unit-tests/timeField.test.js
  test/unit-tests/write.test.js
Labels: ReleaseCandidate

#1368 #1359 fix extra headers
  lib/handlers/fetchHandler.js
  lib/taiko.js
  package-lock.json
  package.json
  test/functional-tests/specs/pageActions.spec
  test/functional-tests/tests/htmlElementAPI.ts
  test/unit-tests/handlers/fetchHandler.test.js
  types/taiko/index.d.ts
Labels: ReleaseCandidate, bug

#1381 #1370 Handle error in a better way
  lib/handlers/runtimeHandler.js
  package-lock.json
  package.json
Labels: ReleaseCandidate, bug
