Repository getgauge/taiko, pull requests merged in 2020-02, with the labels that each got.

#1053 Generate api.json in post-install phase.
  lib/api.json
  lib/documentation.js
  lib/repl/repl.js
  lib/util.js
  package.json
  test/unit-tests/util.test.js
Labels: cla-signed

#1071 Changed the description of the package
  package.json
Labels: cla-signed

#1072 Fix broken link
  docs/layout/partials/header.html
Labels: cla-signed

#1036 Get config
  lib/config.js
  lib/taiko.js
  package-lock.json
  test/unit-tests/config.test.js
Labels: cla-signed

#1077 Update header.html
  docs/layout/partials/header.html
Labels: cla-signed

#1090 Automate release
  .github/workflows/github_release.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  package-lock.json
Labels: cla-signed

#1080 Code style check
  lib/config.js
  lib/taiko.js
  package.json
  test/unit-tests/config.test.js
Labels: SkipRelease, cla-signed

#1096 added support to input emoji
  lib/handlers/inputHandler.js
  lib/taiko.js
  test/unit-tests/write.test.js
Labels: cla-signed

#996 Support for Incognito session
  .eslintrc
  .github/workflows/taiko.yml
  .gitignore
  examples/04-windows-tabs.js
  lib/browserContext.js
  lib/browserFetcher.js
  lib/handlers/targetHandler.js
  lib/taiko.js
  package.json
  test/unit-tests/browserContext.test.js
  test/unit-tests/openBrowser.test.js
Labels: ReleaseCandidate, cla-signed

#1098 Use the right annotation for tableCell documentation
  lib/taiko.js
Labels: ReleaseCandidate, cla-signed

#1086 Chromium download can be skipped when specified in .npmrc
  lib/install.js
Labels: cla-signed, enhancement
