Repository getgauge/taiko, pull requests merged in 2020-04, with the labels that each got.

#1157 Fix beforeunload API
  lib/handlers/pageHandler.js
  lib/taiko.js
  test/unit-tests/beforeunload.test.js
Labels: cla-signed

#1173 Auto update chromium to stable version
  .github/workflows/update_chromium.yml
  getVersion.js
  lib/browserFetcher.js
  updateChromium.js
Labels: bug

#1187 fix element screenshot with proximity selectors
  lib/handlers/domHandler.js
  package.json
  test/unit-tests/screenshot.test.js
Labels: ReleaseCandidate, bug

#1194 fix screenshot for specific element with index
  lib/handlers/pageHandler.js
  test/unit-tests/screenshot.test.js
  test/unit-tests/test-util.js
Labels: bug

#1125 added experimental typescript support
  README.md
  package.json
  types/taiko/index.d.ts
Labels: ReleaseCandidate, cla-signed, feature

#1200 Replace babylon with @babel/parser
  lib/repl/awaitEval.js
  package-lock.json
  package.json
Labels: dependencies

#1204 Set up a redirect to list of devices
  bin/taiko.js
  lib/taiko.js
  netlify.toml
Labels: bug

#1206 Select hidden elements
  lib/elementSearch.js
  lib/elementWrapper/elementWrapperFactory.js
  lib/taiko.js
  test/unit-tests/$.test.js
  test/unit-tests/button.test.js
  test/unit-tests/checkbox.test.js
  test/unit-tests/dropDown.test.js
  test/unit-tests/filefield.test.js
  test/unit-tests/image.test.js
  test/unit-tests/link.test.js
  test/unit-tests/listItem.test.js
  test/unit-tests/radioButton.test.js
  test/unit-tests/textBox.test.js
  test/unit-tests/textMatch.test.js
  types/taiko/index.d.ts
Labels: feature

#1214 #164 allow setting browser args from env var
  docs/layout/partials/header.html
  lib/taiko.js
  test/unit-tests/openBrowser.test.js
Labels: feature

#1222 Refactor unit test
  test/unit-tests/$.test.js
  test/unit-tests/beforeunload.test.js
  test/unit-tests/browserContext.test.js
  test/unit-tests/button.test.js
  test/unit-tests/checkbox.test.js
  test/unit-tests/clear.test.js
  test/unit-tests/click.test.js
  test/unit-tests/color.test.js
  test/unit-tests/dropDown.test.js
  test/unit-tests/evaluate.test.js
  test/unit-tests/filefield.test.js
  test/unit-tests/focus.test.js
  test/unit-tests/highlight.test.js
  test/unit-tests/image.test.js
  test/unit-tests/incognito.test.js
  test/unit-tests/isDisabled.test.js
  test/unit-tests/link.test.js
  test/unit-tests/listItem.test.js
  test/unit-tests/openBrowser.test.js
  test/unit-tests/radioButton.test.js
  test/unit-tests/range.test.js
  test/unit-tests/screenshot.test.js
  test/unit-tests/tablecell.test.js
  test/unit-tests/test-util.js
  test/unit-tests/textBox.test.js
  test/unit-tests/textMatch.test.js
  test/unit-tests/timeField.test.js
  test/unit-tests/waitFor.test.js
  test/unit-tests/write.test.js
Labels: tech debt

#1215 #1203 return status code from goto
  lib/handlers/pageHandler.js
  lib/repl/repl.js
  lib/taiko.js
  package-lock.json
  package.json
  test/unit-tests/goto.test.js
  test/unit-tests/handlers/pageHandler.test.js
  types/taiko/index.d.ts
Labels: ReleaseCandidate, feature
