Repository getgauge/taiko, pull requests merged in 2020-10, with the labels that each got.

#1535 Add regex support for text() API
  lib/elementSearch.js
  lib/elementWrapper/helper.js
  lib/taiko.js
  package-lock.json
  package.json
  test/unit-tests/textMatch.test.js
  types/taiko/index.d.ts
  types/taiko/test/selectors.ts
Labels: ReleaseCandidate, feature

#1583 Fix text search for special char
  lib/elementSearch.js
  test/unit-tests/textMatch.test.js
Labels: bug

#1588 #1557 Update $ selector to take a callback
  lib/elementWrapper/dollarWrapper.js
  lib/handlers/runtimeHandler.js
  lib/taiko.js
  test/unit-tests/$.test.js
  types/taiko/index.d.ts
Labels: feature

#1593 Update scroll to nearest
  lib/actions/scrollTo.js
  package-lock.json
  package.json
Labels: ReleaseCandidate, bug

#1617 Make openTab to open a new tab in current browser context
  lib/browserContext.js
  lib/handlers/targetHandler.js
  lib/taiko.js
  test/unit-tests/closeTab.test.js
  test/unit-tests/handlers/targetHandler.test.js
  test/unit-tests/openTab.test.js
  test/unit-tests/switchTo.test.js
Labels: bug

#1602 Add support for multi-select Drop downs
  lib/elementWrapper/dropDownWrapper.js
  lib/elements/dropDown.js
  test/unit-tests/dropDown.test.js
  test/unit-tests/elements/dropDown.test.js
  types/taiko/index.d.ts
Labels: feature

#1581 Fix click
  lib/actions/click.js
  lib/actions/pageActionChecks.js
  lib/config.js
  lib/handlers/inputHandler.js
  lib/taiko.js
  package-lock.json
  package.json
  test/unit-tests/actions/pageActionChecks.test.js
  test/unit-tests/config.test.js
Labels: ReleaseCandidate, bug
