Repository getgauge/taiko, pull requests merged in 2020-08, with the labels that each got.

#1406 #1388 fix class to match mutiple selection
  lib/elementWrapper/helper.js
  test/unit-tests/button.test.js
Labels: bug

#1409 Fix XPath selector example
  README.md
Labels: documentation

#1405 Ignore custom ssl certificates and disable cors security
  lib/browserLauncher.js
  lib/config.js
  lib/taiko.js
  test/unit-tests/config.test.js
  test/unit-tests/test-util.js
Labels: feature

#1391 Add initial shadow dom support
  lib/actions/dragAndDrop.js
  lib/elementSearch.js
  lib/elementWrapper/buttonWrapper.js
  lib/elementWrapper/checkBoxWrapper.js
  lib/elementWrapper/colorWrapper.js
  lib/elementWrapper/dropDownWrapper.js
  lib/elementWrapper/fileFieldWrapper.js
  lib/elementWrapper/radioButtonWrapper.js
  lib/elementWrapper/rangeWrapper.js
  lib/elementWrapper/textBoxWrapper.js
  lib/elementWrapper/timeFieldWrapper.js
  lib/handlers/runtimeHandler.js
  lib/taiko.js
  package-lock.json
  package.json
  test/unit-tests/$.test.js
  test/unit-tests/button.test.js
  test/unit-tests/checkbox.test.js
  test/unit-tests/clear.test.js
  test/unit-tests/click.test.js
  test/unit-tests/color.test.js
  test/unit-tests/radioButton.test.js
  test/unit-tests/range.test.js
  test/unit-tests/textBox.test.js
  test/unit-tests/write.test.js
Labels: ReleaseCandidate, feature

#1418 Print action output when env is set. #1328
  bin/runFile.js
  bin/taiko.js
  docs/configuring_taiko.md
  lib/eventBus.js
  lib/repl/repl.js
Labels: feature

#1422 Add regex support for dropdown text selection
  lib/elements/dropDown.js
  lib/taiko.js
  test/unit-tests/dropDown.test.js
Labels: feature

#1414 #1285 close and reconnect only if target matches active tab
  lib/handlers/targetHandler.js
  lib/taiko.js
  package-lock.json
  package.json
  test/unit-tests/closeTab.test.js
Labels: ReleaseCandidate, bug

#1424 Added support to get element Attribute
  lib/elementWrapper/elementWrapper.js
  lib/elements/element.js
  lib/taiko.js
Labels: feature

#1429 Update text search
  lib/elementSearch.js
  package-lock.json
  package.json
  test/unit-tests/click.test.js
  test/unit-tests/textMatch.test.js
Labels: ReleaseCandidate, feature

#1445 Fix text regression
  lib/elementSearch.js
  lib/handlers/runtimeHandler.js
  test/unit-tests/textMatch.test.js
Labels: bug

#1432 Use identifiers for tabs
  .gitignore
  lib/browserContext.js
  lib/elements/element.js
  lib/handlers/targetHandler.js
  lib/helper.js
  lib/taiko.js
  test/unit-tests/closeTab.test.js
  test/unit-tests/handlers/targetHandler.test.js
  test/unit-tests/incognito.test.js
  test/unit-tests/openTab.test.js
  test/unit-tests/switchTo.test.js
Labels: feature

#1456 scan symlinks recursively, fixes #1449
  lib/util.js
Labels: ReleaseCandidate, bug

#1461 bump version -> 1.0.20
  package.json
Labels: ReleaseCandidate
