Repository getgauge/taiko, pull requests merged in 2020-11, with the labels that each got.

#1667 Pass proper retry interval/timeout to ElementWrapper.elements
  lib/taiko.js
  test/unit-tests/waitFor.test.js
Labels: bug

#1674 Fix handling exception
  lib/handlers/runtimeHandler.js
  lib/taiko.js
  package-lock.json
  package.json
Labels: ReleaseCandidate

#1655 Match input with placeholders
  lib/elementWrapper/textBoxWrapper.js
  package.json
  test/unit-tests/textBox.test.js
Labels: ReleaseCandidate, feature

#1680 #1604 dont close page on windows headful mode
  lib/taiko.js
Labels: bug

#1648 Change lib/taiko adds omitDescription option in evaluate
  lib/taiko.js
Labels: feature
