Repository getgauge/taiko, pull requests merged in 2020-03, with the labels that each got.

#1044 Fix for not allowing setting value on disable drop down field
  lib/elements/dropDown.js
  test/unit-tests/dropDown.test.js
  test/unit-tests/isDisabled.test.js
Labels: cla-signed

#1092 Added check for --window-size argument before adding default value for it when openBrowser is called in headless mode.
  lib/taiko.js
Labels: cla-signed

#1087 Tablecell fixes
  .eslintrc
  .github/workflows/taiko.yml
  lib/config.js
  lib/doActionAwaitingNavigation.js
  lib/elementSearch.js
  lib/handlers/networkHandler.js
  lib/handlers/pageHandler.js
  lib/handlers/targetHandler.js
  lib/logger.js
  lib/taiko.js
  test/functional-tests/server.js
  test/functional-tests/specs/browserActions.spec
  test/functional-tests/tests/pageActions.js
  test/unit-tests/tablecell.test.js
Labels: cla-signed

#1075 add action to make a release when PR is merged, fixes #1074
  .github/workflows/release_on_pr_merge.yml
Labels: cla-signed

#1108 exists to honour custom wait time
  lib/elementWrapper/elementWrapper.js
  test/unit-tests/textMatch.test.js
Labels: cla-signed

#1114 #1066 fix text() to return text value
  lib/elements/element.js
  test/unit-tests/textMatch.test.js
Labels: bug, cla-signed

#1118 Throw error when supplied targetUrl to switchTo is empty #1057
  lib/taiko.js
  test/unit-tests/switchTo.test.js
Labels: bug, cla-signed

#1117 Support for Color API
  lib/elementWrapper/colorWrapper.js
  lib/elementWrapper/elementWrapperFactory.js
  lib/elements/color.js
  lib/elements/colorFinder.js
  lib/taiko.js
  test/unit-tests/color.test.js
Labels: ReleaseCandidate, cla-signed, feature

#1121 Remove duplicate runtime enable to fix switchTo
  lib/taiko.js
  test/functional-tests/specs/browserActions.spec
  test/unit-tests/switchTo.test.js
Labels: bug, cla-signed

#1120 Add a new FAQ page
  docs/FAQ.md
  docs/layout/partials/toc.html
Labels: cla-signed

#1085 Interceptor Exact Match check before Reg Exp
  lib/handlers/networkHandler.js
Labels: bug, cla-signed

#1132 Refactor tests to start and stop server from hooks
  test/functional-tests/package.json
  test/functional-tests/server.js
  test/functional-tests/tests/hooks.js
  test/functional-tests/tests/server.js
Labels: cla-signed

#1136 Fix waiting for loadEventFired
  lib/doActionAwaitingNavigation.js
  lib/taiko.js
  test/unit-tests/goto.test.js
  test/unit-tests/openTab.test.js
Labels: cla-signed

#1135 Configure http headers for a host when not present.
  lib/handlers/networkHandler.js
  lib/taiko.js
  test/unit-tests/goto.test.js
  test/unit-tests/handlers/networkHandler.test.js
Labels: cla-signed

#1130 Automate chromium update
  .github/workflows/update_chromium.yml
  getVersion.js
Labels: cla-signed

#1122 #766 text api to accept exactMatch as option
  lib/elementSearch.js
  lib/taiko.js
  test/unit-tests/textMatch.test.js
Labels: cla-signed

#1138 emit 'input' event on dropdown change, fixes #1127
  lib/elements/dropDown.js
  test/unit-tests/dropDown.test.js
  test/unit-tests/elements/dropDown.test.js
Labels: cla-signed

#1137 #1134 Case insensitive selectors
  lib/elementSearch.js
  lib/taiko.js
  test/unit-tests/checkbox.test.js
  test/unit-tests/radioButton.test.js
  test/unit-tests/textBox.test.js
Labels: cla-signed

#1146 Added .highlight command
  lib/repl/repl.js
  lib/taiko.js
  package-lock.json
  package.json
  test/unit-tests/highlight.test.js
Labels: cla-signed, feature

#1129 #1031 Added support for range API
  lib/elementWrapper/elementWrapperFactory.js
  lib/elementWrapper/rangeWrapper.js
  lib/elements/range.js
  lib/taiko.js
  package.json
  test/unit-tests/range.test.js
Labels: cla-signed, feature

#1151 Fix switchTo to accept regex
  lib/doActionAwaitingNavigation.js
  lib/taiko.js
  test/unit-tests/switchTo.test.js
Labels: ReleaseCandidate, bug, cla-signed

#1150 Incognito Window API
  lib/browserContext.js
  lib/taiko.js
  package.json
  test/unit-tests/incognito.test.js
Labels: bug, cla-signed

#1115 Websocket issue
  lib/elementSearch.js
  lib/elementWrapper/elementWrapper.js
  lib/handlers/runtimeHandler.js
  lib/helper.js
  lib/proximityElementSearch.js
  lib/taiko.js
  package.json
  test/unit-tests/browserContext.test.js
  test/unit-tests/clientProxy.test.js
  test/unit-tests/elementSearch.test.js
  test/unit-tests/helper.test.js
  test/unit-tests/openBrowser.test.js
Labels: bug, cla-signed

#1154 Update package.json and package-lock.json
  package-lock.json
  package.json
Labels: cla-signed

#1155 added comment and fixed doc string
  lib/browserContext.js
  lib/taiko.js
Labels: cla-signed

#1156 Add options doc string for text API
  lib/taiko.js
Labels: cla-signed
